server:
  port: 8080

spring:
  datasource:
    username: root
    password: jaboor123
    url: jdbc:mysql://localhost:3306/task_manager
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        generate-ddl: true
      show-sql: true

