server:
  port: 8080

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/task_manager
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        generate-ddl: true
        hbm2ddl:
          auto: update
      show-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html


